### ISSUE TITLE
Getting exception in java on windows

### ISSUE THREAD

**Issue by traylz** [VirgilSecurity/virgil-sdk-java-android#13]
Cannot load resource, because ClassLoader.getResourceAsSteram is not expecting backslashes in path to resource, thus cannot find resource
See ```virgil_crypto_javaJNI::loadNativeLibrary

    java.io.FileNotFoundException: Resource 'windows\amd64\virgil_crypto_java' not found
    Exception in thread "main" java.lang.UnsatisfiedLinkError:     com.virgilsecurity.crypto.virgil_crypto_javaJNI.swig_module_init()V
	at com.virgilsecurity.crypto.virgil_crypto_javaJNI.swig_module_init(Native Method)
	at com.virgilsecurity.crypto.virgil_crypto_javaJNI.<clinit>(virgil_crypto_javaJNI.java:487)
	at com.virgilsecurity.crypto.VirgilBase64.decode(VirgilBase64.java:76)
	at com.virgilsecurity.sdk.client.utils.ConvertionUtils.base64ToString(ConvertionUtils.java:131)
	at com.virgilsecurity.sdk.client.VirgilClient.responseToCard(VirgilClient.java:313)
	at com.virgilsecurity.sdk.client.VirgilClient.getCard(VirgilClient.java:222)

**Comment by andrii-iakovenko** [comment]
Could you provide information, please?
What is your:
- Windows version
- Java version
  How do you add dependency to Virgil libraries?

**Comment by traylz** [comment]
@andrii-iakovenko , Windows 10 Professional
Added dependency as per https://virgilsecurity.com/docs/sdk/java-android/v4.0(latest)/java-android-getting-started for Java.
Java 8 101
I've raised PR to fix this.

**Comment by traylz** [comment]
Also, java 8 101

**Comment by traylz** [comment]
@andrii-iakovlenko, Also, java 8 101

**Comment by andrii-iakovenko** [comment]
Use 4.1.1 version instead of 4.1.0.

**Comment by andrii-iakovenko** [comment]
Use version 4.3.3 which is already available at Maven repository:
http://central.maven.org/maven2/com/virgilsecurity/sdk/parent/4.2.0/
