### ISSUE TITLE
getting exception on quick start example

### ISSUE THREAD

**Issue by PeppeFerrara** [VirgilSecurity/virgil-sdk-java-android#17]
Hi, I have followed the guide and the example at https://github.com/VirgilSecurity/virgil-sdk-java-android/tree/master/samples/quickstart/src/main/java/simpleclient using 4.1.1 and 4.2.2 version, but i have always the same problem:

--- exec-maven-plugin:1.2.1:exec (default-cli) @ mavenproject1 ---
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\USER\AppData\Local\Temp\virgil_crypto_java2317542300731338589: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.virgilsecurity.crypto.virgil_crypto_javaJNI.loadNativeLibrary(virgil_crypto_javaJNI.java:540)
	at com.virgilsecurity.crypto.virgil_crypto_javaJNI.<clinit>(virgil_crypto_javaJNI.java:489)
	at com.virgilsecurity.crypto.VirgilKeyPair.decryptPrivateKey(VirgilKeyPair.java:271)
	at com.virgilsecurity.sdk.crypto.VirgilCrypto.importPrivateKey(VirgilCrypto.java:419)
	at com.mycompany.mavenproject1.NewClass.main(NewClass.java:47)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.375s
Finished at: Tue Dec 20 16:55:08 CET 2016
Final Memory: 5M/123M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project mavenproject1: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

the line 47 that throw exception is 
PrivateKey appKey = crypto.importPrivateKey(appKeyData, appKeyPassword);

 Wich is my mistake?
Thanks
ps. windows 10 home, Java 1.8.0_111

**Comment by andrii-iakovenko** [comment]
Use version 4.2.0 which is already available at Maven repository:
http://central.maven.org/maven2/com/virgilsecurity/sdk/parent/4.2.0/
