### ISSUE TITLE
Exception thrown when running main() in EncryptionWithPublicKey.java

### ISSUE THREAD

**Issue by charlesfranciscodev** [VirgilSecurity/virgil-sdk-java-android#8]
Link: [EncryptionWithPublicKey.java](https://github.com/VirgilSecurity/virgil-sdk-java-android/blob/master/samples/crypto/src/main/java/EncryptionWithPublicKey.java)

I tried this sample code in an Android project and a Java project but both fail at line 59:

`KeyPair keyPair = KeyPairGenerator.generate();`

Stack Trace:

Enter text to encrypt: 
test

Native code library failed to load. 
java.io.FileNotFoundException: Resource 'windows\amd64\virgil_crypto_java' not found
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.virgilsecurity.crypto.virgil_crypto_javaJNI.swig_module_init()V
    at com.virgilsecurity.crypto.virgil_crypto_javaJNI.swig_module_init(Native Method)
    at com.virgilsecurity.crypto.virgil_crypto_javaJNI.<clinit>(virgil_crypto_javaJNI.java:408)
    at com.virgilsecurity.crypto.VirgilKeyPair.generate(VirgilKeyPair.java:52)
    at com.virgilsecurity.sdk.crypto.KeyPairGenerator.generate(KeyPairGenerator.java:77)
    at com.virgilsecurity.sdk.crypto.KeyPairGenerator.generate(KeyPairGenerator.java:49)
    at EncryptionWithPublicKey.main(EncryptionWithPublicKey.java:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by teonit** [comment]
Hello,

You are using wrong library. Add this library to project dependencies: http://mvnrepository.com/artifact/com.virgilsecurity.sdk/android/3.2.4

**Comment by charlesfranciscodev** [comment]
I tried to run again in Android Studio with the library you linked to but I still get the same error.

**Comment by teonit** [comment]
Let me clarify some points.
1. You are building Android application
2. You connected android library
3. But according to stacktrace your code runs outside Android device

It seems you are running your app with main method. In this case your app executed by desktop jvm, installed at your computer. But android library can't be run on desktop jvm because there is no native implementation for non-android platforms in android library.

There are two different library sets:
1. For desktop java:
http://mvnrepository.com/artifact/com.virgilsecurity.sdk/crypto
http://mvnrepository.com/artifact/com.virgilsecurity.sdk/client
2. For Android:
http://mvnrepository.com/artifact/com.virgilsecurity.sdk/android

You should use 'crypto' and 'client' libraries if your code runs on desktop jvm.
Use 'android' library if your code runs on Android.

I believe that you'd like to test some code snippets before you start your Android app. You are doing that with main method, but you shouldn't do that! Just use unit tests.

If you created a new application with Android Studio, an 'ApplicationTest' class was created automatically. You can add method provided below and test it.

``` java
public void testKeyPairGenerator() {
 KeyPair keyPair = KeyPairGenerator.generate();
 assertNotNull(keyPair);
}
```

This code will be run on Android.

**Comment by charlesfranciscodev** [comment]
It works fine now when running the code in an Android app project and using an EditText for user input. Thanks for your help.
